import { DayContent, SongContent, StudySection } from './types';

export const WEEK_TITLE = "Prepare Ye for the Coming of the Bridegroom";
export const WEEK_DATE = "November 17 - November 23, 2025";

export const DEVOTIONAL_DATA: DayContent[] = [
    { id: 'monday', day: 'Monday', date: 'November 17, 2025', title: 'Are You Ready for the Wedding? 💍', text: 'The Savior’s Second Coming is often compared to a bridegroom coming for his bride. This beautiful analogy reminds us that this is an event to be anticipated with joy, not fear. Like the wise virgins in the parable, our daily efforts to live the gospel fill our lamps with oil, ensuring we are ready and waiting to greet Him with gladness when He comes.', prompt: 'Challenge: Identify one small, specific thing you can do this week to "add oil to your lamp." Perhaps it\'s five extra minutes of scripture study, a sincere prayer for a neighbor, or a conscious effort to be more patient with a loved one.', scriptureRef: 'Matthew 25:1-13', scriptureLink: 'https://www.churchofjesuschrist.org/study/scriptures/nt/matt/25?lang=eng#p1', lessonLink: 'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-doctrine-and-covenants-2025/47-doctrine-and-covenants-133-134?lang=eng' },
    { id: 'tuesday', day: 'Tuesday', date: 'November 18, 2025', title: 'Leaving Babylon Behind 🏙️', text: 'In the scriptures, "Babylon" represents worldliness, spiritual bondage, and confusion. The Lord\'s call to "go ye out from Babylon" is an invitation to detach ourselves from the noise and temptations of the world and gather in the safety of Zion—a community of the pure in heart. This isn\'t just a physical move; it\'s a spiritual shift in our priorities, desires, and focus.', prompt: 'Reflection: What aspects of modern "Babylon" (e.g., materialism, contention, digital distractions) are most challenging for you? How can you create more "Zion" in your heart and home this week?', scriptureRef: 'D&C 133:5, 14', scriptureLink: 'https://www.churchofjesuschrist.org/study/scriptures/dc-testament/dc/133?lang=eng#p5', lessonLink: 'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-doctrine-and-covenants-2025/47-doctrine-and-covenants-133-134?lang=eng' },
    { id: 'wednesday', day: 'Wednesday', date: 'November 19, 2025', title: 'Preparation Through Participation 🙏', text: 'Sometimes we wonder if we are "enough" to be ready for the Savior\'s return. Elder Steven D. Shumway taught, "As we participate in God\'s work, we prepare ourselves and others for Christ\'s return." Our callings, ministering, and temple worship are not just items on a to-do list; they are the Lord\'s customized curriculum to help us become more like Him, the very best preparation we can have.', prompt: 'Challenge: This week, approach one of your church responsibilities—whether it\'s ministering, a calling, or family history—with the conscious thought, "This is helping me prepare to meet my Savior." Notice how it changes your perspective.', scriptureRef: 'Moroni 7:48', scriptureLink: 'https://www.churchofjesuschrist.org/study/scriptures/bofm/moro/7?lang=eng#p48', lessonLink: 'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-doctrine-and-covenants-2025/47-doctrine-and-covenants-133-134?lang=eng' },
    { id: 'thursday', day: 'Thursday', date: 'November 20, 2025', title: 'A Great, Not Dreadful, Day ✨', text: 'The scriptures describe the events preceding the Second Coming as both "great and dreadful." While the world may experience turmoil, for the righteous, that day will be anything but dreadful. It will be a day of deliverance, glory, and reunion. As we trust in Jesus Christ, our fear is replaced with faith, and our anxiety is swallowed up in anticipation of His glorious return.', prompt: 'Reflection: When you hear about the "signs of the times," do you feel fear or faith? Ponder the promises in D&C 133:19-56 and choose one promise to focus on that brings you peace.', scriptureRef: 'D&C 133:49', scriptureLink: 'https://www.churchofjesuschrist.org/study/scriptures/dc-testament/dc/133?lang=eng#p49', lessonLink: 'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-doctrine-and-covenants-2025/47-doctrine-and-covenants-133-134?lang=eng' },
    { id: 'friday', day: 'Friday', date: 'November 21, 2025', title: 'Remembering His Loving-Kindness ❤️', text: 'Amidst the grand descriptions of His return, the scriptures tenderly remind us to "mention the loving kindness of [our] Lord, and all that he has bestowed upon [us]." The Second Coming is the ultimate expression of His love and goodness—the fulfillment of His plan to redeem His people and heal the earth. Recognizing His hand in our lives now helps us trust His hand in the future.', prompt: 'Challenge: Take a few minutes today to write down or share with a loved one a specific experience where you felt the Savior\'s loving-kindness. Let gratitude fill your heart and strengthen your faith in Him.', scriptureRef: 'D&C 133:52-53', scriptureLink: 'https://www.churchofjesuschrist.org/study/scriptures/dc-testament/dc/133?lang=eng#p52', lessonLink: 'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-doctrine-and-covenants-2025/47-doctrine-and-covenants-133-134?lang=eng' },
    { id: 'saturday', day: 'Saturday', date: 'November 22, 2025', title: 'Good Citizens in God\'s Kingdom 🏛️', text: 'Doctrine and Covenants 134 clarifies that governments are "instituted of God for the benefit of man." As disciples of Christ, we have a responsibility to be good citizens—to obey, honor, and sustain the law. Our righteous influence in our communities and nations is part of preparing the world for its rightful King, who will "reign over all flesh."', prompt: 'Reflection: How can you be a positive influence for good in your local community or nation? Consider how upholding civic responsibilities can be an expression of your discipleship.', scriptureRef: 'D&C 134:1-2', scriptureLink: 'https://www.churchofjesuschrist.org/study/scriptures/dc-testament/dc/134?lang=eng#p1', lessonLink: 'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-doctrine-and-covenants-2025/47-doctrine-and-covenants-133-134?lang=eng' },
    { id: 'sunday', day: 'Sunday', date: 'November 23, 2025', title: 'Embrace the Future with Faith ☀️', text: 'Ultimately, preparing for the future is an act of faith. President Russell M. Nelson taught us to "embrace the future with faith." We don\'t know the day or the hour, but we know the Savior. We trust His promises. We follow His prophets. By living the gospel with hope and joy, we can confidently look forward to the day when He will stand in our midst, and we will be filled with "songs of everlasting joy."', prompt: 'Challenge: As you partake of the sacrament today, focus on your covenants and the hope they provide for the future. Commit to move forward this week, replacing any worries about the future with faith in your Savior, Jesus Christ.', scriptureRef: 'D&C 133:33', scriptureLink: 'https://www.churchofjesuschrist.org/study/scriptures/dc-testament/dc/133?lang=eng#p33', lessonLink: 'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-doctrine-and-covenants-2025/47-doctrine-and-covenants-133-134?lang=eng' }
];

export const YM_DATA: DayContent[] = [
    { id: 'monday', day: 'Monday', date: 'November 17, 2025', title: 'Game Day is Coming! 🏈', text: 'This week\'s lesson is all about preparing for the Second Coming. Think of it like the ultimate Super Bowl. The Savior is coming back, and we\'re on His team. We don\'t know the exact time of the game, but we know it\'s coming. The Lord asks us to "hearken" and get ready now, so we\'re prepared for the big day!', prompt: 'Challenge: What\'s one thing you can do this week to get "spiritually in shape" for the Savior\'s return? Maybe it\'s reading your scriptures for 10 extra minutes or doing a service for someone without being asked.', scriptureRef: 'D&C 133:1-3', scriptureLink: 'https://www.churchofjesuschrist.org/study/scriptures/dc-testament/dc/133?lang=eng#p1', lessonLink: 'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-doctrine-and-covenants-2025/47-doctrine-and-covenants-133-134?lang=eng' },
    { id: 'tuesday', day: 'Tuesday', date: 'November 18, 2025', title: 'Choose Your Team: Zion or Babylon? ⚔️', text: 'The scriptures tell us to "go ye out from Babylon" and gather to Zion. Babylon represents all the worldly distractions and pressures that pull us away from God—the stuff that makes us spiritually weak. Zion is where we stand together, united and strong in the gospel. It\'s about choosing who you follow and where you find your strength.', prompt: 'Challenge: Identify one "Babylon" influence in your life (like a bad habit, negative media, or peer pressure). Now, think of one "Zion" activity you can replace it with.', scriptureRef: 'D&C 133:5, 9', scriptureLink: 'https://www.churchofjesuschrist.org/study/scriptures/dc-testament/dc/133?lang=eng#p5', lessonLink: 'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-doctrine-and-covenants-2025/47-doctrine-and-covenants-133-134?lang=eng' },
    { id: 'wednesday', day: 'Wednesday', date: 'November 19, 2025', title: 'Great, Not Dreadful 🤯', text: 'We hear about earthquakes, wars, and chaos when people talk about the Second Coming, calling it the "great and dreadful day." But that\'s only half the story! For those who are trying to follow Christ, the "great" part will completely outweigh the "dreadful." It’s a day of deliverance and glory for the righteous. Don\'t fear the signs; see them as signs that the King is coming!', prompt: 'Reflection: When you hear about unsettling world events, how can you shift your focus from fear to faith in the Savior\'s ultimate victory?', scriptureRef: 'D&C 110:16', scriptureLink: 'https://www.churchofjesuschrist.org/study/scriptures/dc-testament/dc/110?lang=eng#p16', lessonLink: 'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-doctrine-and-covenants-2025/47-doctrine-and-covenants-133-134?lang=eng' },
    { id: 'thursday', day: 'Thursday', date: 'November 20, 2025', title: 'The Ultimate Victory Lap 🏆', text: 'Forget the scary stuff for a minute and picture this: When the Savior returns, He will be so full of glory the sun will "hide his face in shame." The faithful will be filled with "songs of everlasting joy." It\'s not an ending; it\'s the beginning of His reign and the ultimate victory celebration. This is the moment all of history has been building toward.', prompt: 'Challenge: Listen to an epic, uplifting song today (like a movie soundtrack or a powerful hymn). As you listen, imagine the joyful return of the Savior described in the scriptures.', scriptureRef: 'D&C 133:33, 49', scriptureLink: 'https://www.churchofjesuschrist.org/study/scriptures/dc-testament/dc/133?lang=eng#p33', lessonLink: 'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-doctrine-and-covenants-2025/47-doctrine-and-covenants-133-134?lang=eng' },
    { id: 'friday', day: 'Friday', date: 'November 21, 2025', title: 'Priesthood Prep 💪', text: 'So how do we actually get ready? One of the best ways is by magnifying your priesthood. Every time you prepare, bless, or pass the sacrament, minister to someone, or serve in your quorum, you are preparing to meet the Savior. As Elder Steven D. Shumway taught, "In earnestly seeking to represent the Savior, we become more like Him. That is the best preparation."', prompt: 'Challenge: Look for an extra opportunity to use your priesthood to serve someone today. It could be a family member, a friend, or someone in your quorum.', scriptureRef: 'D&C 133:7-8', scriptureLink: 'https://www.churchofjesuschrist.org/study/scriptures/dc-testament/dc/133?lang=eng#p7', lessonLink: 'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-doctrine-and-covenants-2025/47-doctrine-and-covenants-133-134?lang=eng' },
    { id: 'saturday', day: 'Saturday', date: 'November 22, 2025', title: 'Obey, Honor, and Sustain 🇺🇸', text: 'It might seem like a topic change, but Doctrine and Covenants 134 is about respecting governments and laws. Why is that part of preparing for Christ? Because being His disciple means having integrity everywhere, including as a citizen. The Lord "instituted [governments] for the benefit of man." Honoring the law (when it doesn\'t conflict with God\'s law) is a way we show respect for His order.', prompt: 'Reflection: Think about a law or rule you follow (at school, at home, on the road). How does following that rule help create order and benefit everyone?', scriptureRef: 'D&C 134:1-2', scriptureLink: 'https://www.churchofjesuschrist.org/study/scriptures/dc-testament/dc/134?lang=eng#p1', lessonLink: 'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-doctrine-and-covenants-2025/47-doctrine-and-covenants-133-134?lang=eng' },
    { id: 'sunday', day: 'Sunday', date: 'November 23, 2025', title: 'Ready and Waiting 🙏', text: 'At the end of the day, preparing for the Second Coming isn\'t about fear or a crazy checklist. It\'s about knowing the Savior and loving Him. The scriptures invite us to "mention the loving kindness of [our] Lord." As you take the sacrament today, think about His love and sacrifice for you. Because of Him, we don\'t have to be afraid. We can look forward to His return with hope and joy.', prompt: 'Challenge: During the sacrament today, make a specific mental list of three things you are grateful for that the Savior has done for you personally. Hold on to that feeling of gratitude throughout the day.', scriptureRef: 'D&C 133:52-53', scriptureLink: 'https://www.churchofjesuschrist.org/study/scriptures/dc-testament/dc/133?lang=eng#p52', lessonLink: 'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-doctrine-and-covenants-2025/47-doctrine-and-covenants-133-134?lang=eng' }
];

export const YW_DATA: DayContent[] = [
    { id: 'monday', day: 'Monday', date: 'November 17, 2025', title: 'The Ultimate \'Get Ready With Me\' 💁‍♀️', text: 'We watch "Get Ready With Me" videos for big events like prom or a first date, but the scriptures invite us to a spiritual GRWM for the most important event in history: the Second Coming of Jesus Christ! The Lord asks us to "prepare yourselves for the great day" that is coming. This isn\'t about fear; it\'s about excitedly getting our hearts and lives ready to meet the person who loves us most.', prompt: 'Challenge: This week, pick one small thing you can do to spiritually "get ready." It could be saying a more heartfelt prayer, reading your scriptures for five extra minutes, or doing an act of service for someone in your family.', scriptureRef: 'D&C 133:10', scriptureLink: 'https://www.churchofjesuschrist.org/study/scriptures/dc-testament/dc/133?lang=eng#p10', lessonLink: 'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-doctrine-and-covenants-2025/47-doctrine-and-covenants-133-134?lang=eng' },
    { id: 'tuesday', day: 'Tuesday', date: 'November 18, 2025', title: 'Choose Your Vibe: Zion or Babylon? 💖', text: 'The scriptures talk about two symbolic places: Babylon and Zion. Think of Babylon as the world\'s vibe—full of comparison, drama, and temporary happiness. The Lord invites us to "go ye out from Babylon." In contrast, Zion is a place of unity, peace, and love. It\'s the feeling you get at girls\' camp, in the temple, or with true friends. We choose to live in Zion every time we choose kindness, purity, and faith.', prompt: 'Reflection: Where do you feel the spirit of Zion in your life? What is one "Babylon" influence (like a social media account or a negative habit) you can step away from today?', scriptureRef: 'D&C 133:5', scriptureLink: 'https://www.churchofjesuschrist.org/study/scriptures/dc-testament/dc/133?lang=eng#p5', lessonLink: 'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-doctrine-and-covenants-2025/47-doctrine-and-covenants-133-134?lang=eng' },
    { id: 'wednesday', day: 'Wednesday', date: 'November 19, 2025', title: 'The Best Day EVER! 🎉', text: 'Forget what you\'ve seen in movies about the end of the world. For those who love and follow Jesus, His return will be the most joyful day ever! The scriptures promise we will be "filled with songs of everlasting joy." His glory will be so bright that it will outshine the sun. This isn\'t an event to dread; it\'s the ultimate reunion party that we get to look forward to.', prompt: 'Challenge: Listen to the hymn "Come, Ye Children of the Lord" (#58). As you listen, picture the joyful scenes described in the scriptures and think about what you are most excited for when the Savior returns.', scriptureRef: 'D&C 133:33', scriptureLink: 'https://www.churchofjesuschrist.org/study/scriptures/dc-testament/dc/133?lang=eng#p33', lessonLink: 'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-doctrine-and-covenants-2025/47-doctrine-and-covenants-133-134?lang=eng' },
    { id: 'thursday', day: 'Thursday', date: 'November 20, 2025', title: 'He Remembers You ❤️', text: 'When Jesus comes again, He will show the marks in His hands and feet and say, "I have graven thee upon the palms of my hands." The same Savior who will come in majesty and glory is the one who knows you personally—your name, your struggles, and your heart. He has shown His "loving kindness" throughout your life. His return is the ultimate proof that His love for you is constant and personal.', prompt: 'Reflection: Take a moment to "mention the loving kindness" of the Lord in your own life. Write down in your journal three ways you have seen His goodness and love for you personally.', scriptureRef: 'D&C 133:52-53', scriptureLink: 'https://www.churchofjesuschrist.org/study/scriptures/dc-testament/dc/133?lang=eng#p52', lessonLink: 'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-doctrine-and-covenants-2025/47-doctrine-and-covenants-133-134?lang=eng' },
    { id: 'friday', day: 'Friday', date: 'November 21, 2025', title: 'Don\'t Be Scared, Be Prepared 💪', text: 'It\'s okay to feel a little nervous about the signs of the times—wars, earthquakes, and commotion can sound scary. But President Nelson reminds us that as we prepare, we don\'t need to fear. The "great and dreadful day" will be "great" for the righteous! When you feel anxious, remember that every step you take toward Christ, like choosing the right or being kind, helps replace that fear with faith and peace.', prompt: 'Challenge: The next time you feel worried about the future or things in the world, say a prayer and ask Heavenly Father to help you feel the peace that comes from trusting in His Son.', scriptureRef: 'Matthew 24:6', scriptureLink: 'https://www.churchofjesuschrist.org/study/scriptures/nt/matt/24?lang=eng#p6', lessonLink: 'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-doctrine-and-covenants-2025/47-doctrine-and-covenants-133-134?lang=eng' },
    { id: 'saturday', day: 'Saturday', date: 'November 22, 2025', title: 'You\'re on the Welcoming Committee! 👋', text: 'Preparing for the Second Coming isn\'t just about us. The Lord has asked us to help prepare the world! You are part of His welcoming committee. Every time you share your testimony, invite a friend to church, serve someone in need, or just live as a disciple of Christ, you are helping to "prepare the way of the Lord." You have an important part to play in this amazing work.', prompt: 'Challenge: Be part of the welcoming committee today. Share something you love about the gospel with a friend or on social media, or do a simple act of service to help someone feel the Savior\'s love.', scriptureRef: 'D&C 133:37', scriptureLink: 'https://www.churchofjesuschrist.org/study/scriptures/dc-testament/dc/133?lang=eng#p37', lessonLink: 'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-doctrine-and-covenants-2025/47-doctrine-and-covenants-133-134?lang=eng' },
    { id: 'sunday', day: 'Sunday', date: 'November 23, 2025', title: 'Rules for a Reason 🚦', text: 'Sometimes we think of laws and rules (both God\'s and man\'s) as restrictive. But the Lord teaches that governments and laws are created "for the benefit of man" to help us live in peace and safety. Just like traffic laws prevent chaos on the roads, God\'s commandments protect us from spiritual danger and lead us to true freedom and happiness. Obeying them shows our trust in Him.', prompt: 'Reflection: Think about a commandment that has brought you peace or protected you. How has obeying God\'s laws blessed your life and helped you feel more free?', scriptureRef: 'D&C 134:1', scriptureLink: 'https://www.churchofjesuschrist.org/study/scriptures/dc-testament/dc/134?lang=eng#p1', lessonLink: 'https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-doctrine-and-covenants-2025/47-doctrine-and-covenants-133-134?lang=eng' }
];

export const SONGS_DATA: SongContent[] = [
    { id: 'monday', day: 'Monday', title: 'Are You Ready for the Wedding? 💍', devotionalText: 'The Savior’s Second Coming is often compared to a bridegroom coming for his bride. This beautiful analogy reminds us that this is an event to be anticipated with joy, not fear. Like the wise virgins in the parable, our daily efforts to live the gospel fill our lamps with oil, ensuring we are ready and waiting to greet Him with gladness when He comes.', 
        hymnTitle: 'Rejoice, the Lord Is King!', 
        hymnLink: 'https://www.youtube.com/watch?v=T7tltg8fcwM', 
        hymnAnalysis: 'This triumphant hymn perfectly captures the joyful anticipation described in the devotional. Instead of focusing on the fear that can sometimes accompany discussions of the Second Coming, the hymn commands us to "rejoice!" The lyrics invite us to "lift up the heart" and "lift up the voice," reflecting the attitude of the wise who are prepared to greet the Bridegroom with gladness. The music\'s regal and celebratory tone reinforces the idea that we are preparing for a royal wedding, a glorious reunion with our King. Listening to this hymn can shift our perspective on preparation from a burden to a joyful act of love and anticipation for His glorious return.', 
        songTitle: 'When He Comes Again', 
        songArtist: 'Marilee', 
        songLink: 'https://www.youtube.com/watch?v=4P_mAW-kcNs', 
        songAnalysis: 'This beloved children\'s song tenderly explores the heart of preparation. It asks a simple, profound question: "I wonder, when he comes again, will I be ready there?" The devotional challenges us to add small drops of oil to our lamps through daily acts of kindness and study. This song reflects that same principle, suggesting that our readiness is built on simple, Christlike actions like being "gentle and kind and good." The song reminds us that the grand event of the Second Coming is met with small, personal preparations. Its sweet, simple melody helps us focus on the individual change of heart required to be ready and waiting with joy when He appears.' },
    { id: 'tuesday', day: 'Tuesday', title: 'Leaving Babylon Behind 🏙️', devotionalText: 'In the scriptures, "Babylon" represents worldliness, spiritual bondage, and confusion. The Lord\'s call to "go ye out from Babylon" is an invitation to detach ourselves from the noise and temptations of the world and gather in the safety of Zion—a community of the pure in heart. This isn\'t just a physical move; it\'s a spiritual shift in our priorities, desires, and focus.', 
        hymnTitle: 'Let Zion in Her Beauty Rise', 
        hymnLink: 'https://www.youtube.com/watch?v=2ECFF9hxjoI', 
        hymnAnalysis: 'This hymn is a direct response to the Lord\'s call to "go ye out from Babylon". It paints a beautiful picture of the destination: Zion, a place of "beauty," "glory," and "fame." The lyrics contrast the "darkness" of the world with the light and safety of a covenant community. The devotional explains that leaving Babylon is a "spiritual shift," and this hymn provides the motivation for that shift by describing the peace and holiness we are striving for. The melody is gentle yet firm, evoking a sense of steadfast purpose. It inspires us to actively build Zion in our hearts and homes, creating a sacred space free from the world\'s confusion and contention.', 
        songTitle: 'Zion - original mashup', 
        songArtist: 'Blake Gillette', 
        songLink: 'https://www.youtube.com/watch?v=JBG_G_iwHNs', 
        songAnalysis: 'This energetic and hopeful mashup captures the active, joyful nature of building Zion. The devotional explains that leaving Babylon is a "spiritual shift in our priorities," and this song serves as an anthem for that new focus. By weaving together powerful themes from hymns like "Hope of Israel," the song frames the gathering to Zion not as a passive retreat, but as a dynamic mission. It gives a voice to the "pure in heart" who are actively working to create a holy community. The music\'s driving rhythm and passionate vocals can inspire us to answer the reflection question with purpose, motivating us to do our part to leave the world\'s confusion behind and establish Zion\'s peace in our own hearts and homes.' },
    { id: 'wednesday', day: 'Wednesday', title: 'Preparation Through Participation 🙏', devotionalText: 'Sometimes we wonder if we are "enough" to be ready for the Savior\'s return. Elder Steven D. Shumway taught, "As we participate in God\'s work, we prepare ourselves and others for Christ\'s return." Our callings, ministering, and temple worship are not just items on a to-do list; they are the Lord\'s customized curriculum to help us become more like Him, the very best preparation we can have.', 
        hymnTitle: 'Called to Serve', 
        hymnLink: 'https://www.youtube.com/watch?v=H9OqRPEWdcA', 
        hymnAnalysis: 'This hymn is a powerful anthem for the principle of "preparation through participation." The devotional states that our responsibilities are the Lord\'s "customized curriculum" to help us become more like Him. The hymn\'s lyrics, "Called to serve him, heav\'nly King of glory," frame our service not as a mundane task but as a divine appointment. The energetic, marching tempo instills a sense of purpose and forward movement, aligning perfectly with the idea of actively preparing for Christ\'s return. Singing or listening to this song can transform our perspective, helping us see our callings and ministering assignments as sacred opportunities to arm ourselves "with swords of truth and righteousness" and get ready to meet our Savior.', 
        songTitle: 'Glorious', 
        songArtist: 'David Archuleta', 
        songLink: 'https://www.youtube.com/watch?v=GytW_rgr0RM', 
        songAnalysis: 'This uplifting song speaks directly to the feeling of inadequacy mentioned in the devotional when we wonder if we are "enough." Its core message is that even our seemingly small and imperfect efforts can be made glorious through the grace of God. The lyrics "You can be glorious" and "a symphony of notes... will play a song of hope" perfectly align with the idea that our individual participation—our callings, our ministering—are essential notes in God\'s grand composition. Listening to this song helps fulfill the day\'s challenge by changing our perspective, reminding us that the Lord doesn\'t require perfection, only our willing participation, which He then magnifies to prepare us for His return.' },
    { id: 'thursday', day: 'Thursday', title: 'A Great, Not Dreadful, Day ✨', devotionalText: 'The scriptures describe the events preceding the Second Coming as both "great and dreadful." While the world may experience turmoil, for the righteous, that day will be anything but dreadful. It will be a day of deliverance, glory, and reunion. As we trust in Jesus Christ, our fear is replaced with faith, and our anxiety is swallowed up in anticipation of His glorious return.', 
        hymnTitle: 'The Lord Is My Light', 
        hymnLink: 'https://www.youtube.com/watch?v=2-TChnk8zM0', 
        hymnAnalysis: 'This hymn serves as a powerful antidote to the fear that can arise when contemplating the "dreadful" signs of the times. Its central message, "The Lord is my light; then why should I fear?" speaks directly to the devotional\'s theme of replacing fear with faith. The lyrics are a declaration of trust in God\'s power to save and protect. When the devotional asks if we feel fear or faith, this hymn provides the answer. The steady, confident melody builds a feeling of security and peace, reminding us that with Christ as our "light and salvation," we have no need to be afraid. It helps us focus on the "great" and glorious aspects of His return, seeing it as a day of ultimate deliverance.', 
        songTitle: 'When I Found You', 
        songArtist: 'Madilyn Paige', 
        songLink: 'https://www.youtube.com/watch?v=gflWpvNiMe4', 
        songAnalysis: 'This contemporary song captures the emotional journey from anxiety to faith. The devotional explains that for the righteous, the Second Coming will be a day of "deliverance, glory, and reunion," not dread. This song\'s message of becoming "fearless" through faith in a higher power resonates with that promise. The lyrics speak of finding strength and light when surrounded by darkness, which is a perfect metaphor for navigating the turmoil of the last days. The song\'s uplifting build and powerful chorus can inspire listeners to consciously choose faith over fear, trusting that the Savior\'s return is something to be anticipated with hope, not anxiety.' },
    { id: 'friday', day: 'Friday', title: 'Remembering His Loving-Kindness ❤️', devotionalText: 'Amidst the grand descriptions of His return, the scriptures tenderly remind us to "mention the loving kindness of [our] Lord, and all that he has bestowed upon [us]." The Second Coming is the ultimate expression of His love and goodness—the fulfillment of His plan to redeem His people and heal the earth. Recognizing His hand in our lives now helps us trust His hand in the future.', 
        hymnTitle: 'Count Your Blessings', 
        hymnLink: 'https://www.youtube.com/watch?v=RlMvUEw4g2c', 
        hymnAnalysis: 'This hymn is the perfect practical application of the devotional\'s message. The scripture\'s invitation to "mention the loving kindness of our Lord" is precisely what this hymn instructs us to do. The lyrics guide us to "name them one by one" and see what God has done. This process of intentional gratitude helps us recognize God\'s hand now, which, as the devotional says, helps us trust Him for the future. The simple, cheerful melody makes the act of counting blessings feel joyful, not like a chore. It directly supports the challenge to identify specific experiences of the Lord\'s love, promising that doing so will bring surprise and comfort.', 
        songTitle: 'Consider the Lilies', 
        songArtist: 'The Crosbys', 
        songLink: 'https://www.youtube.com/watch?v=FSDTJRLpV28', 
        songAnalysis: 'This beautiful version provides a powerful meditation on the Savior\'s constant, tender care, which is the essence of His "loving-kindness". The devotional encourages us to recognize God\'s hand now to build trust for the future. The song\'s message, drawn from the Savior\'s own teaching, does exactly that by pointing to the lilies and the birds as evidence of the Father\'s awareness and provision. It gently rebukes our fears, reminding us that if God cares so meticulously for the simplest of His creations, His loving-kindness towards us is infinitely greater. The peaceful, flowing music invites a spirit of trust and gratitude, helping us feel secure in His love as we prepare for the future.' },
    { id: 'saturday', day: 'Saturday', title: 'Good Citizens in God\'s Kingdom 🏛️', devotionalText: 'Doctrine and Covenants 134 clarifies that governments are "instituted of God for the benefit of man." As disciples of Christ, we have a responsibility to be good citizens—to obey, honor, and sustain the law. Our righteous influence in our communities and nations is part of preparing the world for its rightful King, who will "reign over all flesh."', 
        hymnTitle: 'Do What Is Right', 
        hymnLink: 'https://www.youtube.com/watch?v=Y0k7JSb4KKg', 
        hymnAnalysis: 'This hymn encapsulates the core principle of Christian citizenship. The devotional explains that being a good citizen is an "expression of your discipleship," and this hymn\'s recurring charge is to "do what is right; let the consequence follow". This applies perfectly to our civic duties. Obeying the law, being an honest employee, and serving in our community are all ways we do what is right. The hymn promises that as we do so, angels will "guard thee and give thee crowning success." This mirrors the idea that our righteous influence helps prepare the world for its King. The hymn\'s resolute and steady tune inspires integrity and courage in our public and private lives.', 
        songTitle: 'Dare to Do Right', 
        songArtist: 'Saints Channel', 
        songLink: 'https://www.youtube.com/watch?v=wkeMAfSlAuo', 
        songAnalysis: 'While a children\'s song, its message is a powerful reminder for all ages about civic and personal integrity. The devotional calls on us to be a "positive influence for good," and this song is a direct call to that standard. The lyrics, "Dare to do right! Dare to be true!" encourage us to uphold our values even when it\'s difficult, which is the foundation of being a righteous influence in the community. It teaches that our individual choices to be honorable and true contribute to a better whole. The song\'s simple, memorable melody reinforces a clear and unwavering commitment to being a good citizen as part of our discipleship.' },
    { id: 'sunday', day: 'Sunday', title: 'Embrace the Future with Faith ☀️', devotionalText: 'Ultimately, preparing for the future is an act of faith. President Russell M. Nelson taught us to "embrace the future with faith." We don\'t know the day or the hour, but we know the Savior. We trust His promises. We follow His prophets. By living the gospel with hope and joy, we can confidently look forward to the day when He will stand in our midst, and we will be filled with "songs of everlasting joy."', 
        hymnTitle: 'Come, Come, Ye Saints', 
        hymnLink: 'https://www.youtube.com/watch?v=4ia3gYSvG8M', 
        hymnAnalysis: 'This historical hymn is a profound anthem about embracing an unknown future with absolute faith. The devotional calls us to replace worry with trust in the Savior as we move forward. The lyrics of "Come, Come, Ye Saints" directly address this, acknowledging that the journey ahead may be difficult ("though hard to you this journey may appear"), but commanding us to proceed with joy ("Gird up your loins; fresh courage take"). The hymn\'s core message—"All is well! All is well!"—is not a statement of easy circumstance, but a declaration of ultimate faith that God is in charge and will consecrate our trials for our good. Its steady, determined melody inspires the very courage and hope needed to "embrace the future with faith".', 
        songTitle: 'Press Forward', 
        songArtist: 'Noelle Bybee', 
        songLink: 'https://www.youtube.com/watch?v=10uSvyuAol8', 
        songAnalysis: 'This song is a modern musical expression of embracing the future with faith. The title itself, "Press Forward," is a call to action rooted in hope. The devotional encourages us to move forward by replacing worry with faith, and this song\'s lyrics provide the motivation: "Press forward with a steadfastness in Christ, having a perfect brightness of hope". The song’s energetic and optimistic melody inspires a feeling of joyful momentum. It acknowledges that the path isn\'t always clear, but we move forward trusting in the Savior. It is a perfect companion to the challenge to commit to moving forward, providing an uplifting soundtrack for our journey of faith.' }
];

export const STUDY_GUIDE_DATA: StudySection[] = [
    {
        title: "Introduction",
        type: 'intro',
        content: 'This guide is designed to help class members apply the principles from these sections to their own lives and to be better prepared to contribute to the class discussion.',
    },
    {
        title: "Background",
        type: 'discussion',
        content: "This week's lesson covers two important revelations. Section 133 of the Doctrine and Covenants was received by Joseph Smith in November 1831. It was intended to be the appendix for the Book of Commandments, the first compilation of the Lord's latter-day revelations. In 1833, before the book could be finished, a mob destroyed the Church's printing press in Missouri, scattering the pages. This revelation, however, was preserved and serves as a powerful call to prepare for the Second Coming of Jesus Christ.\n\nSection 134 was written in August 1835 as a declaration of the Church's beliefs regarding governments and laws. This was a necessary clarification. The early Saints had been violently forced out of Jackson County, Missouri, in 1833 and received no protection or help from the local or national government. This declaration affirmed their belief that governments are instituted by God for the benefit of mankind and that citizens have a responsibility to uphold the law."
    },
    {
        title: "Prepare Ye for the Coming of the Bridegroom",
        type: 'discussion',
        content: "The introduction explains the historical setting for section 133. It was meant to be the concluding chapter, or \"appendix,\" for the Book of Commandments. Despite the violent opposition and destruction of the press, the Lord's words were preserved. This serves as a powerful witness that His work cannot be stopped and His promises will be fulfilled. The core message of this revelation is a repeated call found throughout scripture: leave worldliness (Babylon), build Zion, and prepare the world for the Savior's return.",
        questions: [
            {
                question: "What does the preservation of section 133, despite the destruction of the printing press, teach us about the nature of God's work in the latter days?",
                answer: "It teaches us that God's purposes cannot be frustrated by man. Even when faced with intense opposition and setbacks, His work will roll forward. It shows that His words are enduring and will be made available to His children as He has promised."
            }
        ]
    },
    {
        title: "Jesus Christ calls me to reject Babylon and come to Zion.",
        type: 'discussion',
        content: "Throughout the scriptures, the ancient city of Babylon is used as a symbol for wickedness, worldliness, and spiritual bondage. In contrast, Zion represents the community of the pure in heart, living in unity and righteousness. In these verses, the Lord gives a clear command to \"go ye out from Babylon\" and gather to Zion. This is a call to separate ourselves from the spiritually corrupting influences of the world.",
        quote: "Doctrine and Covenants 133:5, 14: \"Go ye out from Babylon. Be ye clean that bear the vessels of the Lord... Go ye out from among the nations, even from Babylon, from the midst of wickedness, which is spiritual Babylon.\"",
        questions: [
            {
                question: "In a world where we are constantly surrounded by the influences of \"Babylon,\" what are some practical things we can do to \"go... out\" and keep ourselves and our families spiritually clean?",
                answer: "We can be intentional about the media we consume, choosing uplifting content over that which is degrading. We can choose friends who share our values. We can prioritize time for prayer, scripture study, and temple worship over worldly pursuits. It means consciously choosing to live by gospel standards even when they conflict with the world's standards."
            },
            {
                question: "How does gathering to \"Zion\"—whether in our homes, our wards, or the temple—provide safety and peace amid the uncertainties of the world?",
                answer: "Zion is a place of spiritual safety. When we create a Zion-like environment in our homes, we create a refuge from the world. When we participate in our wards, we are strengthened by a community of believers. The temple is the ultimate symbol of Zion on earth, a place where we can feel God's presence and find peace that the world cannot provide."
            }
        ]
    },
    {
        title: "I can prepare now for the Savior’s Second Coming.",
        type: 'discussion',
        content: "Both the preface (Section 1) and the original appendix (Section 133) of the Doctrine and Covenants begin with the same plea from the Lord: \"Hearken, O ye people of my church.\" This emphasizes the critical importance of listening to and obeying His counsel as we prepare for His return. These verses outline specific actions we must take to prepare both ourselves and the world.",
        questions: [
            {
                question: "The manual suggests listing things the Lord wants us to do to (1) prepare ourselves and (2) help prepare the world. Based on verses 1-19, what are some actions that would be on each list?",
                answer: "For ourselves: sanctify ourselves, be sober, pray always, and trim our lamps. For the world: go forth and preach the gospel, warn our neighbors, and gather the Saints from among the nations."
            },
            {
                question: "How does actively participating in the work of preparation, as described in these verses, help replace fear of the Second Coming with joyful anticipation?",
                answer: "The Lord's work is a source of joy. When we are engaged in serving others, fulfilling our callings, and sharing the gospel, we become more like the Savior. This process purifies us and helps us focus on the \"great\" part of that \"great and dreadful day.\""
            }
        ]
    },
    {
        title: "The Second Coming of Jesus Christ will be joyful for the righteous.",
        type: 'discussion',
        content: "While many descriptions of the Second Coming focus on destruction and judgment, these verses paint a picture of a glorious, triumphant, and joyful day for the faithful. We will see the Lord in His glory, hear His voice, and remember His loving-kindness. The faithful, both living and dead, will be crowned with glory and filled with \"songs of everlasting joy.\" It will be a day of redemption and reunion.",
        quote: "Doctrine and Covenants 133:52: \"And they shall mention the loving kindness of their Lord, and all that he has bestowed upon them according to his goodness, and according to his loving kindness, forever and ever.\"",
        questions: [
            {
                question: "What words, phrases, or images in verses 19-56 stand out to you and help you look forward to the Savior's return?",
                answer: "The idea that He will \"stand in the midst of his people\". The image of His glory being so bright that \"the sun shall hide his face in shame\". The promise that the faithful will be \"crowned with glory\" and sing \"songs of everlasting joy\". The tender promise that \"in his love and in his pity he redeemed them\"."
            },
            {
                question: "Why is remembering what the Lord has already done for us a powerful way to prepare to meet Him?",
                answer: "Remembering His past goodness builds our faith and trust in Him for the future. It solidifies our testimony of His personal love for us. When we recognize His hand in our lives now, we can have confidence that His return will be the ultimate expression of His love and mercy for those who have followed Him."
            }
        ]
    },
    {
        title: "\"Governments were instituted of God for the benefit of man.\"",
        type: 'discussion',
        content: "This section clarifies the Church's position on secular governments. It teaches that governments are ordained by God to protect the rights and freedoms of individuals, including religious freedom, and to maintain public order. In return, citizens have a duty to uphold the law and support their government. This was a crucial declaration for the early Saints, who were often falsely accused of rejecting earthly authority.",
        quote: "Articles of Faith 1:12: “We believe in being subject to kings, presidents, rulers, and magistrates, in obeying, honoring, and sustaining the law.”",
        questions: [
            {
                question: "According to Doctrine and Covenants 134: verses 1, 2, and 5, what are the primary responsibilities of governments, and what corresponding duties do citizens have?",
                answer: "Governments are responsible for creating and administering laws for the good and safety of society and to \"secure to each individual the free exercise of conscience, the right and control of property, and the protection of life\". Citizens are responsible for sustaining their government and obeying the law and are encouraged to seek out and uphold leaders who will act with wisdom and honesty."
            }
        ]
    },
    {
        title: "Lesson Summary",
        type: 'summary',
        content: "This week's lesson is a powerful reminder that the Lord is hastening His work and preparing the world for His glorious return. He calls us to leave the wickedness of the world (Babylon) and gather to the safety and righteousness of Zion. By heeding His call, serving others, and remembering His goodness, we can replace any fear of the future with a joyful, faith-filled anticipation of meeting Him. His coming will be a \"great day\" for the righteous. We are also reminded of our civic duty to uphold righteous laws and governments that God has instituted for our benefit."
    }
];